CREATE TABLE IF NOT EXISTS permission (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          description VARCHAR(255) DEFAULT NULL,
                                          PRIMARY KEY (id)
);