
ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO public.person (id, address, first_name, gender, last_name) VALUES (1, 'São Paulo - Brasil', 'Murilo', 'Male', 'Dias');
INSERT INTO public.person (id, address, first_name, gender, last_name) VALUES (2, 'Amapá - SP', 'Maria', 'Female', 'Silva');
INSERT INTO public.person (id, address, first_name, gender, last_name) VALUES (6, 'Franca - SP', 'Garcio', 'Male', 'Madeiros');
INSERT INTO public.person (id, address, first_name, gender, last_name) VALUES (7, 'Franca - SP', 'Gabriela', 'Female', 'Sousa');
INSERT INTO public.person (id, address, first_name, gender, last_name) VALUES (8, 'Ribeirão Preto - SP', 'Júlio', 'Male', 'Tesla');

SELECT pg_catalog.setval('public.person_id_seq', 8, true);


ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);
