CREATE TABLE public.books (
                              id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              author TEXT,
                              launch_date TIMESTAMP NOT NULL,
                              price DECIMAL(65,2) NOT NULL,
                              title TEXT
);